# Generated by Django 4.1 on 2022-11-26 14:06

import activities.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=30, unique=True)),
                ('activity_description', models.CharField(blank=True, max_length=1024)),
                ('points', models.IntegerField()),
                ('evidence_needed', models.CharField(max_length=1024)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(default=datetime.date(2022, 11, 26), validators=[activities.models.validate_year])),
                ('end_date', models.DateField(default=datetime.date(2022, 12, 31), null=True, validators=[activities.models.validate_year])),
                ('is_approved', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(default='', max_length=255)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(default=datetime.date(2022, 11, 26), validators=[activities.models.validate_year])),
                ('end_date', models.DateField(default=datetime.date(2022, 12, 31), validators=[activities.models.validate_year])),
                ('budget', models.IntegerField(blank=True, null=True)),
                ('threshhold', models.IntegerField(validators=[activities.models.validate_budget])),
                ('is_archived', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_owner', to=settings.AUTH_USER_MODEL, validators=[activities.models.validate_exist, activities.models.validate_none])),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('amounts', models.IntegerField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(editable=False)),
                ('is_used', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='earned_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Points',
            },
        ),
        migrations.CreateModel(
            name='ActivitySuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=30)),
                ('activity_description', models.CharField(max_length=1024)),
                ('justification', models.CharField(blank=True, max_length=30, null=True)),
                ('evidence_needed', models.CharField(blank=True, max_length=1024, null=True)),
                ('points', models.IntegerField()),
                ('start_date', models.DateField(default=datetime.date(2022, 11, 26), validators=[activities.models.validate_year])),
                ('end_date', models.DateField(default=datetime.date(2022, 12, 31), null=True, validators=[activities.models.validate_year])),
                ('is_accepted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activitycategory')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityRestorationRequest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=30, unique=True)),
                ('activity_description', models.CharField(blank=True, max_length=1024)),
                ('points', models.IntegerField()),
                ('evidence_needed', models.CharField(max_length=1024)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accpeted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default=('PENDING', 'Pending'), max_length=10)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('archived_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archived_activity_by', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activitycategory')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('date_of_action', models.DateTimeField(validators=[activities.models.validate_date_of_action])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accpeted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default=('PENDING', 'Pending'), max_length=10)),
                ('evidence_needed', models.CharField(default='Provide evidence please', max_length=1024)),
                ('proof_of_action', models.FileField(upload_to='proofs/')),
                ('activity_approval_date', models.DateTimeField(null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.activity')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approver_of_upload', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activitycategory')),
                ('emp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_uploader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.activitycategory'),
        ),
    ]
