# Generated by Django 3.2 on 2022-10-19 11:49

import activities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycategory',
            name='budget',
            field=models.IntegerField(validators=[activities.models.validate_budget]),
        ),
    ]
