# Generated by Django 4.0.6 on 2022-10-24 10:22

import activities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.DateTimeField(null=True, validators=[activities.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.DateTimeField(validators=[activities.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, validators=[activities.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, validators=[activities.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='activityrequest',
            name='date_of_action',
            field=models.DateTimeField(validators=[activities.models.validate_date_of_action]),
        ),
    ]
