# Generated by Django 4.0.6 on 2022-10-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activity_end_date_alter_activity_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityrequest',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
