# Generated by Django 3.2 on 2022-10-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activitycategory_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activitycategory',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
