# Generated by Django 4.0.6 on 2022-11-02 08:50

import activities.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0005_alter_activity_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 31, 0, 0), null=True, validators=[activities.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 10, 50, 41, 982569), validators=[activities.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='budget',
            field=models.IntegerField(blank=True, null=True, validators=[activities.models.validate_budget]),
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 12, 31, 0, 0), null=True, validators=[activities.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_owner', to=settings.AUTH_USER_MODEL, validators=[activities.models.validate_none, activities.models.validate_exist]),
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 2, 10, 50, 41, 981572), null=True, validators=[activities.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='total_budget',
            field=models.IntegerField(),
        ),
    ]
