# Generated by Django 4.0.6 on 2022-11-05 17:49

import activities.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0006_alter_activity_end_date_alter_activity_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.activitycategory'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.DateField(default=datetime.date(2022, 12, 31), null=True, validators=[activities.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 11, 5), validators=[activities.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='budget',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 12, 31), null=True, validators=[activities.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_owner', to=settings.AUTH_USER_MODEL, validators=[activities.models.validate_exist, activities.models.validate_none]),
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 11, 5), null=True, validators=[activities.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='total_budget',
            field=models.IntegerField(validators=[activities.models.validate_budget]),
        ),
    ]
