# Generated by Django 4.0.6 on 2022-11-09 07:48

import activities.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_alter_activity_approved_by_alter_activity_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 11, 9), validators=[activities.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 11, 9), null=True, validators=[activities.models.validate_year]),
        ),
    ]
