# Generated by Django 4.0.6 on 2022-11-09 09:48

import activities.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_alter_activity_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitycategory',
            old_name='total_budget',
            new_name='threshhold',
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 11, 9), validators=[activities.models.validate_year]),
        ),
    ]
