# Generated by Django 4.0.6 on 2022-11-09 10:15

import activities.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_rename_total_budget_activitycategory_threshhold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycategory',
            name='end_date',
            field=models.DateField(default=datetime.date(2022, 12, 31), validators=[activities.models.validate_year]),
        ),
    ]
