# Generated by Django 4.0.6 on 2022-11-24 12:42

import activities.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_alter_activity_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitysuggestion',
            old_name='is_archived',
            new_name='is_accepted',
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 11, 24), validators=[activities.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 11, 24), validators=[activities.models.validate_year]),
        ),
    ]
