# Generated by Django 4.0.6 on 2022-11-24 12:52

import activities.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_rename_is_archived_activitysuggestion_is_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysuggestion',
            name='end_date',
            field=models.DateField(default=datetime.date(2022, 12, 31), null=True, validators=[activities.models.validate_year]),
        ),
        migrations.AddField(
            model_name='activitysuggestion',
            name='points',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitysuggestion',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 11, 24), validators=[activities.models.validate_year]),
        ),
    ]
