# Generated by Django 4.0.6 on 2022-11-29 08:32

import activities.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0015_alter_activity_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityrequest',
            name='submitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 11, 29), validators=[activities.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 11, 29), validators=[activities.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='activityrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accpeted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='activitysuggestion',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 11, 29), validators=[activities.models.validate_year]),
        ),
    ]
