# Generated by Django 4.0.6 on 2022-11-29 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0016_activityrequest_submitter_alter_activity_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityrequest',
            old_name='emp',
            new_name='employee',
        ),
    ]
