# Generated by Django 4.0.6 on 2022-11-29 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0018_alter_activityrequest_activity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityrequest',
            name='is_archived',
        ),
    ]
