# Generated by Django 4.1.3 on 2022-12-06 08:39

import activities.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0021_alter_activity_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='points',
            field=models.IntegerField(validators=[activities.models.validate_negative]),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 12, 6), validators=[activities.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 12, 6), validators=[activities.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='threshhold',
            field=models.IntegerField(validators=[activities.models.validate_budget, activities.models.validate_threshhold]),
        ),
        migrations.AlterField(
            model_name='activitysuggestion',
            name='category',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='activities.activitycategory'),
        ),
        migrations.AlterField(
            model_name='activitysuggestion',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 12, 6), validators=[activities.models.validate_year]),
        ),
    ]
