# Generated by Django 4.0.6 on 2022-12-08 09:16

import activities.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0022_alter_activity_points_alter_activity_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='points',
            field=models.IntegerField(default=0, validators=[activities.models.validate_negative]),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 12, 8), validators=[activities.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 12, 8), validators=[activities.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='activitysuggestion',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 12, 8), validators=[activities.models.validate_year]),
        ),
    ]
