# Generated by Django 4.1.4 on 2022-12-25 11:36

import activities.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0027_alter_activity_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, validators=[activities.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='activitycategory',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, validators=[activities.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='activitysuggestion',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, validators=[activities.models.validate_year]),
        ),
    ]
