# Generated by Django 4.0.6 on 2022-10-24 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='EndDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='StartDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='creator',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CATEGORYOWNER', 'CategoryOwner'), ('EMPLOYEE', 'Employee')], default=('ADMIN', 'Admin'), max_length=20),
        ),
    ]
