# Generated by Django 4.0.6 on 2022-11-02 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_announcement_enddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='EndDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 31, 0, 0)),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='StartDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 10, 50, 41, 965614)),
        ),
    ]
