# Generated by Django 4.0.6 on 2022-11-24 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_announcement_startdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='StartDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 24, 14, 51, 57, 918946)),
        ),
    ]
