# Generated by Django 4.0.6 on 2022-12-18 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0021_userregisterationrequest_accept_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='StartDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 18, 8, 25, 28, 81903)),
        ),
    ]
