# Generated by Django 4.0.6 on 2022-11-05 17:49

import Rewards.models
import Users.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggest_vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=30)),
                ('website', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=1024)),
                ('is_archived', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accpeted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default=('PENDING', 'Pending'), max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('vendor_policy', models.CharField(max_length=5000, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2022, 11, 5, 19, 49, 32, 147275), validators=[Rewards.models.validate_year])),
                ('end_date', models.DateTimeField(default=datetime.datetime(2022, 12, 31, 0, 0), null=True, validators=[Rewards.models.validate_year])),
                ('img', models.ImageField(blank=True, upload_to='images/')),
                ('accepts_voucher', models.BooleanField(default=False)),
                ('accepts_procurement', models.BooleanField(default=False)),
                ('accepts_direct', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(default=Users.models.User, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_day', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2022, 11, 5, 19, 49, 32, 148273), validators=[Rewards.models.validate_year])),
                ('end_date', models.DateTimeField(default=datetime.datetime(2022, 12, 31, 0, 0), validators=[Rewards.models.validate_year])),
                ('points_equivalent', models.IntegerField()),
                ('is_archived', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reward_creator', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rewards.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Redemption_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accpeted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='Pending', max_length=10)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('approved_date', models.DateTimeField(default=datetime.datetime(2022, 11, 5, 19, 49, 32, 148273), null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, validators=[Rewards.models.validate_admin])),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rewards.reward')),
            ],
        ),
        migrations.CreateModel(
            name='budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.IntegerField()),
                ('point', models.IntegerField()),
                ('EGP', models.IntegerField()),
                ('budget_compare', models.IntegerField(null=True)),
                ('year', models.IntegerField(default=2022, validators=[Rewards.models.validate_year_forbudget])),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('Archived_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
