# Generated by Django 3.2 on 2022-10-19 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Rewards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vendors',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rewards',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reward_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rewards',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rewards.vendors'),
        ),
        migrations.AddField(
            model_name='redemption_request',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='redemption_request',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='redemption_request',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rewards.rewards'),
        ),
        migrations.AddField(
            model_name='olddatavendors',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='olddatavendors',
            name='original_vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rewards.vendors'),
        ),
        migrations.AddField(
            model_name='olddatavendors',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_updater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='olddatasuggest_vendor',
            name='original_suggestion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Rewards.suggest_vendor'),
        ),
        migrations.AddField(
            model_name='olddatasuggest_vendor',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendorsuggestion_updater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='olddatarewards',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='olddatarewards',
            name='original_voucher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Rewards.rewards'),
        ),
        migrations.AddField(
            model_name='olddatarewards',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reward_updater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budget',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archiverewards',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archiver_reward', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archiverewards',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archivedvendors',
            name='archived_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_archiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archivedvendors',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archivedvendors',
            name='original_vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rewards.vendors'),
        ),
    ]
