# Generated by Django 4.0.6 on 2022-11-09 07:48

import Rewards.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rewards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='budget_in_point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_budget', models.IntegerField()),
                ('total_budget', models.IntegerField(null=True)),
                ('year', models.IntegerField(default=2022, validators=[Rewards.models.validate_year_forbudget])),
                ('start_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='redemption_request',
            name='approved_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 9, 9, 48, 42, 78308), null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 9, 9, 48, 42, 77138), validators=[Rewards.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 9, 9, 48, 42, 75143), validators=[Rewards.models.validate_year]),
        ),
    ]
