# Generated by Django 4.0.6 on 2022-12-10 08:45

import Rewards.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Rewards', '0002_alter_redemption_request_approved_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redemption_request',
            name='approved_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 10, 45, 23, 361100), editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='creator',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reward_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reward',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 10, 45, 23, 360103), validators=[Rewards.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 10, 10, 45, 23, 358108), validators=[Rewards.models.validate_year]),
        ),
    ]
