# Generated by Django 4.0.6 on 2022-10-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rewards', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='Archived_at',
            field=models.DateTimeField(),
        ),
    ]
