# Generated by Django 4.0.6 on 2022-10-24 10:22

import Rewards.models
import Users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Rewards', '0004_alter_budget_archived_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='year',
            field=models.IntegerField(default=2022, validators=[Rewards.models.validate_year_forbudget]),
        ),
        migrations.AlterField(
            model_name='redemption_request',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, validators=[Rewards.models.validate_admin]),
        ),
        migrations.AlterField(
            model_name='reward',
            name='end_date',
            field=models.DateTimeField(validators=[Rewards.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='reward',
            name='start_date',
            field=models.DateTimeField(validators=[Rewards.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='suggest_vendor',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accpeted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default=('PENDING', 'Pending'), max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='creator',
            field=models.ForeignKey(default=Users.models.User, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='end_date',
            field=models.DateTimeField(null=True, validators=[Rewards.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='start_date',
            field=models.DateTimeField(validators=[Rewards.models.validate_year]),
        ),
    ]
