# Generated by Django 4.0.6 on 2022-10-26 10:20

import Users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Rewards', '0005_alter_budget_year_alter_redemption_request_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='creator',
            field=models.ForeignKey(default=Users.models.User, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
