# Generated by Django 4.0.6 on 2022-11-24 12:42

import Rewards.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rewards', '0006_alter_redemption_request_approved_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redemption_request',
            name='approved_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 24, 14, 42, 49, 49601), null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 24, 14, 42, 49, 48604), validators=[Rewards.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 24, 14, 42, 49, 48604), validators=[Rewards.models.validate_year]),
        ),
    ]
