# Generated by Django 4.0.6 on 2022-11-02 08:50

import Rewards.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rewards', '0006_alter_vendor_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redemption_request',
            name='approved_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 10, 50, 41, 979577), null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 31, 0, 0), validators=[Rewards.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='reward',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 10, 50, 41, 979577), validators=[Rewards.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 31, 0, 0), null=True, validators=[Rewards.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 10, 50, 41, 978580), validators=[Rewards.models.validate_year]),
        ),
    ]
