# Generated by Django 4.0.6 on 2022-11-26 13:14

import Rewards.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rewards', '0008_alter_redemption_request_approved_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggest_vendor',
            name='status',
        ),
        migrations.AlterField(
            model_name='redemption_request',
            name='approved_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 26, 15, 14, 41, 660795), null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 26, 15, 14, 41, 660795), validators=[Rewards.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 26, 15, 14, 41, 659798), validators=[Rewards.models.validate_year]),
        ),
    ]
