# Generated by Django 4.0.6 on 2022-11-28 17:42

import Rewards.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rewards', '0009_remove_suggest_vendor_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redemption_request',
            name='approved_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 28, 19, 42, 47, 721696), null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 28, 19, 42, 47, 721696), validators=[Rewards.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 28, 19, 42, 47, 721696), validators=[Rewards.models.validate_year]),
        ),
    ]
