# Generated by Django 4.0.6 on 2022-12-05 09:34

import Rewards.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Rewards', '0015_remove_vendor_accepts_direct_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redemption_request',
            options={'verbose_name_plural': 'redemption request'},
        ),
        migrations.AlterField(
            model_name='redemption_request',
            name='approved_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='redemption_request',
            name='approved_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 5, 11, 34, 17, 34203), editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='redemption_request',
            name='employee',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, validators=[Rewards.models.validate_admin]),
        ),
        migrations.AlterField(
            model_name='redemption_request',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accpeted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='ACCEPTED', max_length=10),
        ),
        migrations.AlterField(
            model_name='reward',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 5, 11, 34, 17, 34203), validators=[Rewards.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 5, 11, 34, 17, 33205), validators=[Rewards.models.validate_year]),
        ),
    ]
